### ISSUE TITLE
Not allowed to load local resource error on Chrome

### ISSUE THREAD

**Issue by oleg-butko** [fregante/webext-base-css#12]
Using

`@import 'chrome://global/skin/in-content/common.css' (min--moz-device-pixel-ratio:0); `

in `webext-base.css`

leads to the error:

`Not allowed to load local resource: chrome://global/skin/in-content/common.css`

on Chromium 102.0.5005.115 (Official Build) (64-bit)

**Comment by fregante** [comment]
You can ignore the error. That style is Firefox-only, but causes no issues in Chrome
