### ISSUE TITLE
In Safari, title sticks to next text/input field

### ISSUE THREAD

**Issue by rakleed** [fregante/webext-base-css#13]
In Safari, the title sticks to the next text/input field. Problem due to https://github.com/fregante/webext-base-css/blob/2413047ab31894cac6d4202a78982fc802ee33bd/webext-base.css#L63-L67

<details><summary>Screenshot</summary>

![Screenshot 2023-01-30 at 22 00 31](https://user-images.githubusercontent.com/19418601/215603841-ff6fd68f-3912-4d51-b748-10b069531a54.png)

</details>

**Comment by fregante** [comment]
This kind of style fix isn't the intent of this package, which only tries to provide a useful _base_ to have native-looking pages.

I wonder however if https://github.com/fregante/webext-base-css/issues/10 will fix this
