### ISSUE TITLE
Misaligned labels on checkboxes in Firefox

### ISSUE THREAD

**Issue by frederikb** [fregante/webext-base-css#16]
Hi,

first of all thanks for this stylesheet (and [webext-options-sync](https://github.com/fregante/webext-options-sync)): I'm happily using both in [frederikb/bookmarksync](https://github.com/frederikb/bookmarksync).

## Problem Description

I've noticed the following visual discrepancy between Chrome and Firefox in regard to checkboxes, which is probably (?) not intended. The label is vertically misaligned with its checkbox in Firefox.

### Chrome (Version 123.0.6312.105 (Official Build) (arm64))
![image](https://github.com/fregante/webext-base-css/assets/232148/1f2a0062-4c00-475a-8ecb-1d349bc0b6bf)

`options.html` from this repo:
![image](https://github.com/fregante/webext-base-css/assets/232148/a002d07a-3143-4aaf-b7fb-06a6a40a7719)

### Firefox (124.0.2 (64-bit))
![image](https://github.com/fregante/webext-base-css/assets/232148/5f85914b-d377-4fa5-a2d0-12f0d72ffe0d)

`options.html` from this repo:
![image](https://github.com/fregante/webext-base-css/assets/232148/c0f49732-8cc8-4111-ac64-c95d7e1c736b)

## Workaround

The issue disappears when I remove the following Firefox only style from `webext-base.css`:

```css
input[type="checkbox"] {
  vertical-align: -0.4em;
}
```

That line dates back from four years ago according to git blame. There might have been some browser style changes since then? Can you confirm that this is a regression from since then?

**Comment by fregante** [comment]
Do you use Refined GitHub? If the browser changed styles, you should see the same issue there. 

If not, there might be a specific DOM style you have to follow for that to work. There's a demo extension in this repo for reference https://github.com/fregante/webext-base-css/blob/main/options.html

**Comment by frederikb** [comment]
I've installed Refined GitHub and see the same issue there in Firefox (FYI, I'm on macOS 14.2.1, I forgot to mention):

![image](https://github.com/fregante/webext-base-css/assets/232148/4eff97fb-a8ea-4df5-b758-f8a27796c365)

The checkboxes and labels for the features details section look fine, but then again the markup for that is quite different as well.
